
[workspace]
resolver = "2"
members = [
    "crates/*",
    "contracts/*",
    "examples/increment",
    "examples/errors",
    "examples/cross_contract/*",
]

exclude = [
    "crates/smartdeploy-macros",
    "crates/smartdeploy-sdk",
    "contracts/*",
    "examples/increment",
    "examples/errors",
    "examples/cross_contract/*",
]


[profile.release-with-logs]
inherits = "release"
debug-assertions = true

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

# [workspace.dependencies.soroban-sdk]
# version = "0.7.0"
# git = "https://github.com/stellar/rs-soroban-sdk"
# rev = "8abd3353c728f09ee1c8a2544f67a853e915afc2"


[workspace.dependencies]
# loam-sdk = { path = "../../loam/crates/loam" }
# loam-sdk-core-riff = { path = "../../loam/crates/loam-core" }
loam-sdk = { git = "https://github.com/loambuild/loam-sdk", tag = "v0.5.0" }
loam-sdk-core-riff = { git = "https://github.com/loambuild/loam-sdk", tag = "v0.5.0" }
clap = { version = "4.1.8", features = [
    "derive",
    "env",
    "deprecated",
    "string",
] }
base64 = "0.13.0"
thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
serde-aux = "4.1.2"
hex = "0.4.3"
num-bigint = "0.4"
tokio = { version = "1", features = ["full"] }
soroban-cli = "0.8.7"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
