#!/usr/bin/env bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd );
ID="$(cat $SCRIPT_DIR/contract_id.txt)"

NAME=$1
shift

CONTRACT_ID=$(soroban contract invoke --source default --id $ID -- fetch_contract_id --deployed_name $NAME | jq -r)
soroban contract invoke --id "$CONTRACT_ID" -- $@