[package]
name = "smartdeploy-cli"
description = "Smartdeploy CLI"
authors = ["Willem Wyndham <willem@ahalabs.dev>"]
license = "Apache-2.0"
readme = "README.md"
version = "0.0.1"
edition = "2021"
rust-version = "1.70"
autobins = false
default-run = "smartdeploy"

[[bin]]
name = "smartdeploy"
path = "src/bin/main.rs"

[package.metadata.binstall]
pkg-url = "{ repo }/releases/download/v{ version }/{ name }-{ version }-{ target }{ archive-suffix }"
bin-dir = "{ bin }{ binary-ext }"


[lib]
name = "smartdeploy_cli"
path = "src/lib.rs"
doctest = false

[dependencies]
soroban-cli = { git = "https://github.com/ahalabs/soroban-tools", rev = "2966e7ac9cbcc9f408b80f4aa21c3b76ccf064c6"}
clap = { version = "4.1.8", features = [
    "derive",
    "env",
    "deprecated",
    "string",
] }

clap-cargo-extra = "0.3.0"

thiserror = "1.0.31"
serde = "1.0.82"
serde_derive = "1.0.82"
serde_json = "1.0.82"
serde-aux = "4.1.2"
tokio = { version = "1", features = ["full"] }
termcolor = "1.1.3"
termcolor_output = "1.0.1"
clap_complete = "4.1.4"
rand = "0.8.5"
sha2 = "0.10.6"
csv = "1.1.6"
dirs = "4.0.0"
toml = "0.5.9"
itertools = "0.10.5"
strsim = "0.10.0"
heck = "0.4.1"
cargo_metadata = "0.15.4"
pathdiff = "0.2.1"
shlex = "1.1.0"

[dev-dependencies]
assert_cmd = "2.0.4"
assert_fs = "1.0.7"
predicates = "2.1.5"
