
name: Tests
on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: test RPC
    runs-on: ubuntu-22.04
    env:
        SOROBAN_RPC_URL: http://localhost:8000/soroban/rpc
        SOROBAN_NETWORK_PASSPHRASE: "Standalone Network ; February 2017"
        SOROBAN_ACCOUNT: default
    services:
      rpc:
        image: stellar/quickstart:v423-testing
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          NETWORK: local
          ENABLE_SOROBAN_RPC: true
        options: >-
          --health-cmd "curl --no-progress-meter --fail-with-body -X POST \"http://localhost:8000/soroban/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}' && curl --no-progress-meter \"http://localhost:8000/friendbot\" | grep '\"invalid_field\": \"addr\"'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 50
    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@nextest
    - uses: cargo-bins/cargo-binstall@main
    - run: just setup
    - run: just build
    - run: cargo nextest run
    - run: just clean
    - run: just publish_all
    - run: just deployed_contracts