
name: local

on:
  push:
    branches: [main, release/**]
  pull_request:

jobs:
  test:
    name: Test CLI
    runs-on: ubuntu-22.04
    services:
      rpc:
        image: stellar/quickstart:testing
        ports:
          - 8000:8000
        env:
          ENABLE_LOGS: true
          NETWORK: local
          ENABLE_SOROBAN_RPC: true
    steps:
    - uses: actions/checkout@v3
    - run: "curl --fail-with-body -X POST \"http://localhost:8000/soroban/rpc\" -H 'Content-Type: application/json' -d '{\"jsonrpc\":\"2.0\",\"id\":8675309,\"method\":\"getNetwork\"}'"
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - uses: taiki-e/install-action@just
    - uses: taiki-e/install-action@cargo-binstall
    - run: rustup update
    - run: rustup target add wasm32-unknown-unknown
    - run: just setup
    - run: just clean
    - run: just publish_all
    - run: just deployed_contracts